### ISSUE TITLE
Add table jira_issue - issue-links

### ISSUE THREAD

**Issue by agwilkinson** [turbot/steampipe-plugin-jira#123]
Hi there,

Can you please add a data for "Issue Links" within the jira_issue table ?

The API is:

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-links/#api-group-issue-links

Kind Regards

  -Alex

**Comment by ParthaI** [comment]
Closing this issue since the details for issue links are already included in the `jira_issue` table.

**Comment by e-gineer** [comment]
@ParthaI Nice - perhaps we should add this as en example for the table? I couldn't see any reference to the links on the table or examples when considering this question so didn't realize they were buried down in there!

**Comment by ParthaI** [comment]
Absolutely, @e-gineer, I'll include the example query in the table document. Thank you!
