### ISSUE TITLE
jira_board only fetching first page of results

### ISSUE THREAD

**Issue by rayl-bln** [turbot/steampipe-plugin-jira#126]
**Describe the bug**
`select * from jira_board` only returns the first page of boards I have access to.

If I use the REST API directly, i see these values
```json
{
  "maxResults": 50,
  "startAt": 0,
  "total": 168,
  "isLast": false,
  "values": [
...
```

I've confirmed that i'm able to use the `startAt` parameter to see all 168 boards using the REST API from the command line. The subsequent pages just aren't being fetched by the plugin, it only sees the first page of 50 results.

**Steampipe version (`steampipe -v`)**
Steampipe v0.23.2

**Plugin version (`steampipe plugin list`)**
0.14.0 

**To reproduce**
`select count()* from jira_board`

**Expected behavior**
The query should return the full number of boards I have access to, instead of just the first 50.

**Additional context**

**Comment by ParthaI** [comment]
Hi @rayl-bln, I apologize for the issue you are experiencing. I have raised a [PR](https://github.com/turbot/steampipe-plugin-jira/pull/127) to address this issue, and it should resolve the issue, allowing you to fetch all the results correctly.

It would be great if you would like to try out the changes in the PR branch `issue-126` and share your experience with us.

Thanks!

**Comment by rayl-bln** [comment]
Tested and confirmed working on go version go1.21.0 linux/amd64, Ubuntu 22.04.2 LTS on WSL2.  thanks for the quick response!
