### ISSUE TITLE
Add table jira_user_settings_details from profile & visibility.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-jira#26]
**References**
if its possible to query the user profile settings, to confirm whether the users are enabled with 2 factor authentication or not.
https://id.atlassian.com/manage-profile/security

**Comment by rajlearner17** [comment]
@sayan133 can you pls update the API link here indicating there is no API available

**Comment by sayan133** [comment]
As of now, there is no direct API available for this operation.
JIRA REST API: https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/
