### ISSUE TITLE
Add table jira_settings_system to fetch the settings info.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-jira#28]
**References**
JIRA > System > General Configurations provides the JIRA setup information. 
![image](https://user-images.githubusercontent.com/26873346/124590484-d1122080-de78-11eb-97fa-2ad450047325.png)

**Comment by sayan133** [comment]
Not getting any direct API to fetch these details. However, some details like, 'Allow users to vote on issues', 'Allow users to watch issues', etc are available in the table `jira_global_settings`. @LalitTurbot can you please confirm?
