### ISSUE TITLE
Add table jira_site_access to fetch the site access info

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-jira#35]
**References**
JIRA > Settings > User Management > Site Access
<img width="993" alt="Screenshot 2021-07-19 at 4 46 19 PM" src="https://user-images.githubusercontent.com/46913995/126166331-ccbebd03-c9ff-4d0d-9d65-313214d09816.png">

**Comment by sayan133** [comment]
As of now, no direct API is available for these settings.
Rest API Doc: https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/
