### ISSUE TITLE
Adding "resolved" field into jira_issue table

### ISSUE THREAD

**Issue by jinhong-** [turbot/steampipe-plugin-jira#55]
**Is your feature request related to a problem? Please describe.**
I want to be able to know what the resolution date of an issue is to help calculate cycle time, when a bug was closed, etc

**Describe the solution you'd like**
To have the "resolved" field exposed

**Describe alternatives you've considered**
Currently using "updated" field. However updated is different from "resolved", as an update could mean changing of description, adding of labels, etc which is different from resolution date

**Additional context**
Information on the JQL field [here](https://support.atlassian.com/jira-service-management-cloud/docs/advanced-search-reference-jql-fields/#Advancedsearchingfieldsreference-ResolutionResolution)

**Comment by misraved** [comment]
Thanks @jinhong- for using Steampipe 👍.

The use case looks extremely promising. We have opened a [PR](https://github.com/turbot/steampipe-plugin-jira/pull/56) which adds the `resolution_date` column to the `jira_issue` table. It would be great if you could locally build the changes and check if it suffices your requirement.

Steps to check:
- clone the `steampipe-plugin-jira` repo into your local by using the following commands
```
git clone https://github.com/turbot/steampipe-plugin-jira.git
cd steampipe-plugin-jira
```
- Checkout to the PR branch
```
git checkout add-resolution-date-column-jira-issue-table
```
- Run the make command
```
make
```
- Run the steampipe query to get the issue resolution date
```
select title, resolution_date, status from jira_issue
```

Please let us know if it resolves your issue. 👍
