### ISSUE TITLE
select * from jira_backlog_issue

### ISSUE THREAD

**Issue by jeanpauldevooght** [turbot/steampipe-plugin-jira#61]
**Describe the bug**
Whenever I run a query against ira_backlog_issue, I get the error message
`Warning: executeQueries: query 1 of 1 failed: ERROR: rpc error: code = Unknown desc = request failed. Please analyze the request body for more details. Status code: 400 (SQLSTATE HV000)`
I cannot find any information from the underlying go-jira lib request object despite setting STEAMPIPE_LOG_LEVEL to trace.
The equivalent curl command works from the CLI
`curl --request GET --user email:token --url "https://domain.atlassian.net/rest/agile/1.0/board/70/backlog?startAt=140&maxResults=1&expand=names" --header "Accept: application/json"`

**Steampipe version (`steampipe -v`)**
v0.15.1

**Plugin version (`steampipe plugin list`)**
v0.5.0

**To reproduce**
I had some help from the Slack group but I don't see why the default queries would fail for me.
I have noticed 400 or 403 status codes with the following tables
```
jira_backlog_issue: 400
jira_advanced_setting: 403
jira_group: 403
jira_project_role: 403
jira_sprint: 400
jira_workflow: 403
```

**Expected behavior**
I would expect to run the default queries against my Atlassian domain using my username and token.

**Additional context**
The underying library's message about checking the request body is frustrating if there is nothing to check

**Comment by misraved** [comment]
@jeanpauldevooght Sorry to hear that you are running into issues with the jira plugin.

I was able to run the above query without running into any errors. 
- Could you please share how many backlog issues are you trying to run the query against?
- Has the plugin been configured correctly as per https://hub.steampipe.io/plugins/turbot/jira#configuration
- Are you only getting this error for the default queries? Are you able to run other queries mentioned in the table docs - https://hub.steampipe.io/plugins/turbot/jira/tables/jira_backlog_issue

**Comment by cbruno10** [comment]
@jeanpauldevooght From our Slack discussion, I recall you were having issues around compiling the Jira plugin locally from the `add-debug-backlog-issues` branch. Were you ever able to successfully build that plugin version and run against it?

Also, can you please run the following queries and share the results here:
- `select * from jira_backlog_issue limit 1`
- `select * from jira_backlog_issue where board_id = 70`

**Comment by misraved** [comment]
@jeanpauldevooght I believe the issue could be with the permissions. I found this link online which might be helpful in figuring out the permissions - https://support.atlassian.com/jira-cloud-administration/docs/manage-project-permissions/

Alternatively, you could have used the following query -
```
select
  id,
  name,
  actor_id,
  actor.display_name,
  actor.account_type,
  actor.active as actor_status
from
  jira_project_role as role,
  jsonb_array_elements_text(actor_account_ids) as actor_id,
  jira_user as actor
where
  actor_id = actor.account_id;
 ```
 but I realised that you are getting a `403` error for the table (https://hub.steampipe.io/plugins/turbot/jira/tables/jira_project_role#table-jira_project_role).

**Comment by misraved** [comment]
Thanks @jeanpauldevooght for the input. I looked into different articles pertaining to Jira permission model and I think it could be specific to the company's set up on Atlassian cloud.

Relevant thread - https://community.atlassian.com/t5/Jira-Software-questions/How-can-I-give-access-to-a-project-board-backlog-to-an-external/qaq-p/1193944

**Comment by cbruno10** [comment]
@jeanpauldevooght Sorry about the bad log message format, I've fixed that in a commit I just pushed to the `add-debug-backlog-issues` branch. Can you please try again? Thanks!

**Comment by jdevoo** [comment]
Just wanted to close saying this issue can be fixed for both `jira_backlog_issue` and `jira_sprint` by moving / expanding the following statement after `client.Do` instead of `client.NewRequest`

```
if isNotFoundError(err) || strings.Contains(err.Error(), "400") {
  return nil, nil
}
```
I arrived at this by focusing on the two problematic `select * from` and comparing with `jira_epic` which would not return a 400 error code. Without this test, the plugin processes a collection of boards most of which lead to a 400 error and never returned records for those boards that were OK.

I am not sure how to fix the TODO in `table_jira.sprint` about not getting board id details. I had noticed that queries with `where board_id` would not help me skip the undesirable boards.

**Comment by cbruno10** [comment]
@jeanpauldevooght Thank you very much for testing the fix and identifying some areas where we had inconsistent error handling! I've just pushed https://github.com/turbot/steampipe-plugin-jira/commit/6c907ec65461c61defde4dc33168b7f255dd7f57, which cleans up some inconsistencies in error handling in all tables, and I've moved around some of the error handling code that was in the incorrect places, like you had identified, in several tables.
