### ISSUE TITLE
Allow authentication to on-premise jira using personal access token

### ISSUE THREAD

**Issue by robert-n-harris** [turbot/steampipe-plugin-jira#66]
Per my discussion with Cody on 10/26/2022, requesting added capability to authenticate to on-prem Jira instance with personal access token (PAT) as shown in https://github.com/andygrunwald/go-jira/blob/main/onpremise/examples/bearerauth/main.go#L15-L18

**Comment by cbruno10** [comment]
Thanks for raising an issue @robert-n-harris !

For anyone interested in adding this capability, here are some suggestions on where to get started:
- Add new configuration arguments (`personal_access_token`) to support passing in a personal access token with support in https://github.com/turbot/steampipe-plugin-jira/blob/main/jira/connection_config.go
- Update the `connect` function in https://github.com/turbot/steampipe-plugin-jira/blob/main/jira/utils.go#L16 to use this new config arg, based on the example in https://github.com/andygrunwald/go-jira/blob/main/onpremise/examples/bearerauth/main.go
  - If `token` and `personal_access_token`, I'm not sure which one should take precedence, but for now `token` will be used if both are passed in,  as Jira on-prem is deprecated and Jira Cloud is part of their main strategy moving forward.

**Comment by jpambrun** [comment]
I was taking a look at the suggestion and it seems this would require migrating to the unraleased go-jira v2?
