### ISSUE TITLE
Connection configuration is not available through env variables

### ISSUE THREAD

**Issue by vm-diegocruz** [turbot/steampipe-plugin-jira#74]
**Describe the bug**
To add the connection configuration using env variables is not available as in other plugins, the documentation only defines through the `jira.spc`. Environment variables should be an option.

**Steampipe version (`steampipe -v`)**
v0.17.4

**Plugin version (`steampipe plugin list`)**
v0.8.0

**To reproduce**
The [documentation](https://hub.steampipe.io/plugins/turbot/jira) is not defining the env variables available to be exported, also, there is no reference in the code docs.

**Expected behavior**
Passing the configuration (base_url, username and password) using env variables should be an option like in other plugins like AWS, Azure, GCP, Github, etc.

**Comment by e-gineer** [comment]
Adding support for environment variables is fairly straight forward if anyone would like to attempt it:
1. Choose env var names similar to those used in other Jira applications / terraform / etc.
2. [Update this function](https://github.com/turbot/steampipe-plugin-jira/blob/72a133305ffeba104b7409d9486b84313a3eb9b9/jira/utils.go#L16-L65) to grab the env var data. See [this function](https://github.com/turbot/steampipe-plugin-planetscale/blob/9e18dd0adb58d1f7b946cdd1d72655c2a0d73f2e/planetscale/utils.go#L14-L63) as an example to follow.
3. Update the docs/index.md to detail the env var settings.

**Comment by cbruno10** [comment]
Removing stale label to keep the issue available as a good first issue.
