### ISSUE TITLE
CSV Output Column\Row Truncation

### ISSUE THREAD

**Issue by johngarner-dwp** [turbot/steampipe-plugin-jira#76]
**Describe the bug**
When using CSV output some of the rows appear to be truncated.

```shell
❯ steampipe query
Welcome to Steampipe v0.18.6
For more information, type .help
> .output csv
```

```sql
select key,
       epic_key,
       substring(summary,1,30) "summary",
       assignee_display_name,
       components,
       labels,
       priority,
       created,
       reporter_display_name,
       status
from jira_issue
where project_key = 'PKEY'
and status <> 'Done'
and reporter_display_name in ('Reporter 1','Reporter 2')
order by priority desc, length(title), title asc;
```

An example of the problem returned rows (as displayed) are...

```sql
08T12:35:21+01:00,Reporter 1,Backlog
07-04T14:55:21+01:00,Reporter 1,Backlog
14:40:21Z,Reporter 1,Backlog
,"[""16805"",""16725""]","[""Label 1"",""Label 2"",""Label 3"",""Label 4""]",High,2022-12-16T12:49:54Z,Reporter 1,Backlog
```

This  appears to be mostly on the `created` column but there are other occurrences that are on `assignee_display_name` column.

**Steampipe version (`steampipe -v`)**

```shell
❯ steampipe -v
Steampipe v0.18.6
```

**Plugin version (`steampipe plugin list`)**

```shell
❯ steampipe plugin list
+----------------------------------------------------+---------+-------------+
| Installed Plugin                                   | Version | Connections |
+----------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/theapsgroup/gitlab@latest | 0.2.2   | gitlab      |
| hub.steampipe.io/plugins/turbot/aws@latest         | 0.94.0  | aws         |
| hub.steampipe.io/plugins/turbot/jira@latest        | 0.8.0   | jira        |
| hub.steampipe.io/plugins/turbot/steampipe@latest   | 0.6.0   | steampipe   |
+----------------------------------------------------+---------+-------------+
```

**To reproduce**
As above.

**Expected behavior**
Complete rows with all queried column data returned.

**Additional context**
None.

**Comment by karanpopat** [comment]
Hey @johngarner-dwp, thanks for your continuous feedback on the Jira plugin. Sorry that you've hit that bump!

Had quick questions regarding this issue

1. Can you confirm if the results are getting truncated even when you set `.output` to `json` or `table`?
2. Can you also try whether you are facing the same issue with the latest Steampipe CLI version, which is `v0.20.5`?

**Comment by johngarner-dwp** [comment]
@karanpopat thanks for looking into this...

I'm using `Steampipe v0.20.5` and the output is as expected for csv output so it can be closed.
